repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && PYTHONPATH=$(git rev-parse --show-toplevel) uv run pytest tests/ --cov=src.mcp_suite --cov-report=term-missing -v'
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-commit]

      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        exclude: \.venv/

      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
        exclude: \.venv/

      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [python]
        exclude: \.venv/

      # - id: mypy
      #   name: mypy
      #   entry: uv run mypy
      #   language: system
      #   types: [python]
      #   exclude: \.venv/
      #   args: ["--ignore-missing-imports"] 