#################################
#################################
# CI-Linter Pipeline GitHub Actions #
#################################
#################################
name: CI-Linter Pipeline

on:
  push:
    branches-ignore: [master, main]  # Skip CI on pushes to master/main (adjust as needed)
  pull_request:
    branches: [master, main]         # Run CI for pull requests targeting master/main

jobs:
  build:
    name: Lint Code Base and Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      # --------------------------------------------
      # Stage 1: Checkout the Repository
      # --------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full Git history

      # --------------------------------------------
      # Stage 2: Run GitHub Super Linter
      # --------------------------------------------
      - name: Lint Code Base with Super Linter
        uses: super-linter/super-linter@v5
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_OPENAPI: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_JSCPD: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_MARKDOWN: false

      # --------------------------------------------
      # Stage 3: Set Up Python Environment
      # --------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Specify your desired Python version

      # --------------------------------------------
      # Stage 3.5: Install uv package installer
      # --------------------------------------------
      - name: Install uv
        run: |
          pip install uv
        continue-on-error: true  # Allow next steps to run even if this fails

      # --------------------------------------------
      # Stage 4: Install Project Dependencies
      # --------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          # Explicitly install pytest-cov to fix coverage issues
          pip install pytest pytest-cov
        continue-on-error: true  # Allow next steps to run even if this fails

      # --------------------------------------------
      # Stage 5: Run Tests with Coverage (CI Only)
      # --------------------------------------------
      - name: Run tests with coverage
        run: |
          # Run pytest with coverage if src directory exists
          if [ -d "src" ]; then
            python -m pytest --cov=src/ --cov-report=term-missing -v || echo "Tests failed but continuing..."
          else
            # Fallback if src directory doesn't exist
            python -m pytest -v || echo "Tests failed but continuing..."
          fi
        continue-on-error: true

      # --------------------------------------------
      # Stage 6: Run Black for Code Formatting (CI Only)
      # --------------------------------------------
      - name: Run Black
        run: |
          if command -v black >/dev/null 2>&1; then
            python -m black . --check || echo "Black check failed but continuing..."
          else
            python -m pip install black
            python -m black . --check || echo "Black check failed but continuing..."
          fi
        continue-on-error: true

      # --------------------------------------------
      # Stage 7: Run isort for Import Order Checks (CI Only)
      # --------------------------------------------
      - name: Run isort
        run: |
          if command -v isort >/dev/null 2>&1; then
            python -m isort . --check || echo "isort check failed but continuing..."
          else
            python -m pip install isort
            python -m isort . --check || echo "isort check failed but continuing..."
          fi
        continue-on-error: true